---
- name: Install prerequisites
  hosts: 'main_servers'
  remote_user: 'ubuntu'
  gather_facts: false
  become: yes
  tasks:
    - name: Install Python 2.x
      raw: which python || sudo apt-get update && sudo apt-get install -qq -y python-simplejson
      register: python_check
      changed_when: python_check.stdout is not search('/usr/bin/python')

- name: Install buildandtell server for website, wiki, forum, monitoring server and more
  hosts: 'main_servers'
  remote_user: 'ubuntu'
  become: yes
  vars:
    - playbook_name: 'server'
  roles:
    #- { role: 'common' }
    #- { role: 'postgres' }
    #- { role: 'swapfile', swapfile_size: 2GB, swapfile_file: /swapfile, tags: [swapfile] }
    #- { role: 'ntp' }
    #- { role: 'php' }
    #- { role: 'nginx', tags: [nginx]}
    #- { role: 'certbot', tags: [certbot], domains: ['buildandtell.xyz','*.buildandtell.xyz']}
    - { role: 'dokuwiki', tags: [dokuwiki] }
    - { role: 'wikianimal', domain: 'wiki.buildandtell.xyz', tags: [wikianimal] }
    - { role: 'homepage' }
    #- { role: 'ruby' , become_user: 'ubuntu' }
      #- { role: 'ruby' }
      #- { role: 'website' }
      #- { role: 'discourse' }
      #- { role: 'mastodon' }
      #- { role: 'monitoring' }
