- name: Create database user {{ mastodon_db_user }}
  postgresql_user:
    name: "{{ mastodon_db_user }}"
    #password: "{{ mastodon_db_pass }}" ident authentication
    encrypted: yes
    login_unix_socket: "{{ mastodon_db_login_unix_socket }}"
    role_attr_flags: CREATEDB
