---
- stat: path=/etc/letsencrypt/live/{{ mastodon_host }}/fullchain.pem
  register: letsencrypt_cert

- name: Install letsencrypt cert
  command: "certbot certonly --webroot -d {{ mastodon_host }} -w {{ mastodon_home }}/{{ mastodon_path }}/public/ --email contact@buildandtell.xyz --non-interactive --agree-tos"
  when: not letsencrypt_cert.stat.exists
  become_user: root
  notify: reload nginx

- name: remove symlink to acme.conf
  file:
    path: "/etc/nginx/sites-enabled/acme.conf"
    state: absent

- name: symlink to mastodon.conf
  file:
    src: "/etc/nginx/sites-available/mastodon.conf"
    dest: "/etc/nginx/sites-enabled/mastodon.conf"
    state: link
  when:
    - mastodon_host is defined
  notify: reload nginx

- name: Set letsencrypt cronjob
  cron:
    name: "letsencrypt renew"
    minute: "15"
    hour: "0"
    job: "certbot renew"
  notify: reload nginx

