---
- include: repositories.yml
  when: os_family == "debian"

- include: database.yml
  become: true
  become_user: postgres

- include: packages.yml

- include: user.yml

- import_role:
    name: ruby
  become_user: mastodon

- include: mastodon.yml
  become_user: mastodon

- include: nginx.yml

- include: letsencrypt.yml

- include: setup-mastodon.yml
  become_user: mastodon
  tags:
    - setup mastodon
