---
- name: Clone mastodon
  git:
    repo: "https://github.com/tootsuite/mastodon.git"
    dest: "{{ mastodon_home }}/{{mastodon_path}}"
    clone: true

- name: Update to latest version
  shell: "git fetch; git checkout $(git tag -l | grep -v 'rc[0-9]*$' | sort -V | tail -n 1)"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Bundle install
  shell: "~/.rbenv/shims/bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Yarn install
  command: yarn install --pure-lockfile
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"

- name: Copy systemd mastodon-sidekiq
  template:
    src: mastodon-sidekiq.service.j2
    dest: /etc/systemd/system/mastodon-sidekiq.service
  become: true
  become_user: root

- name: Copy systemd mastodon-web.service 
  template:
    src: mastodon-web.service.j2
    dest: /etc/systemd/system/mastodon-web.service
  become: true
  become_user: root

- name: Copy systemd mastodon-streaming.service
  template:
    src: mastodon-streaming.service.j2
    dest: /etc/systemd/system/mastodon-streaming.service
  become: true
  become_user: root

- name: Media cleanup cronjob
  cron:
    name: "media cleanup"
    minute: "15"
    hour: "1"
    job: "cd {{ mastodon_home }}/{{ mastodon_path }} && RAILS_ENV=production /home/mastodon/.rbenv/shims/bundle exec rake mastodon:media:remove_remote"

- stat: path={{ mastodon_home }}/{{ mastodon_path }}/.env.production
  register: production_config

- name: Migrate database
  shell: "RAILS_ENV=production ~/.rbenv/shims/bundle exec rails db:migrate"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"
  when: production_config.stat.exists

- name: Precompile assets
  shell: "RAILS_ENV=production ~/.rbenv/shims/bundle exec rails assets:precompile"
  args:
    chdir: "{{ mastodon_home }}/{{ mastodon_path }}"
  when: production_config.stat.exists

- name: Enable mastodon-web
  service:
    name: mastodon-web.service
    enabled: yes
    state: started
  become_user: root

- name: Enable mastodon-streaming
  service:
    name: mastodon-streaming.service
    enabled: yes
    state: started
  become_user: root

- name: Enable mastodon-sidekiq
  service:
    name: mastodon-sidekiq.service
    enabled: yes
    state: started
  become_user: root

#- name: Restart mastodon-web
#  command: systemctl restart mastodon-web.service
#  when: production_config.stat.exists
#
#- name: Restart mastodon-streaming
#  command: systemctl restart mastodon-streaming.service
#  when: production_config.stat.exists
#
#- name: Restart mastodon-sidekiq
#  command: systemctl restart mastodon-sidekiq.service
#  when: production_config.stat.exists
