---

- name: Copy nginx config
  template: 
    src: mastodon.conf.j2
    dest: /etc/nginx/sites-available/mastodon.conf
  when:
    - mastodon_host is defined
  
- name: Copy acme config
  template: 
    src: acme.conf.j2
    dest: /etc/nginx/sites-available/acme.conf

- name: symlink acme.conf
  file:
    src: "/etc/nginx/sites-available/acme.conf"
    dest: "/etc/nginx/sites-enabled/acme.conf"
    state: link

- name: restart nginx
  service:
    name: nginx
    state: reloaded

- name: Create log directory
  file:
    path: "{{ mastodon_home }}/logs"
    state: directory
    owner: root
    group: root
    mode: 0700
  become_user: root

- name: Create access log file
  file:
    path: "{{ mastodon_home }}/logs/access.log"
    state: touch

- name: Create error log file
  file:
    path: "{{ mastodon_home }}/logs/access.log"
    state: touch