---
- name: copy nginx config
  template: 
    src: mastodon.conf.j2
    dest: /etc/nginx/sites-available/mastodon.conf
  when:
    - mastodon_host is defined

- name: symlink to mastodon.conf
  file:
    src: "/etc/nginx/sites-available/mastodon.conf"
    dest: "/etc/nginx/sites-enabled/mastodon.conf"
    state: link
  when:
    - mastodon_host is defined
  
- name: create log directory
  file:
    path: "{{ mastodon_home }}/logs"
    state: directory
    owner: root
    group: root
    mode: 0700
  become_user: root

- name: create access log file
  file:
    path: "{{ mastodon_home }}/logs/access.log"
    state: touch

- name: create error log file
  file:
    path: "{{ mastodon_home }}/logs/access.log"
    state: touch
  notify: reload nginx
