---
# file: /roles/common/tasks/main.yml

- name: 'update apt cache'
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: 'install git'
  apt:
    name: 'git'
    state: 'present'

- include: fail2ban.yml

- include: ufw.yml