---
# file: /roles/common/tasks/main.yml

- name: 'update apt cache'
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: 'install git'
  apt:
    name: 'git'
    state: 'present'

- name: 'install fail2ban'
  apt:
    name: 'fail2ban'
    state: 'present'

- name: 'copy fail2ban config'
  copy:
    src: 'jail.local'
    dest: '/etc/fail2ban/jail.local'
  notify: 'restart fail2ban'

#- name: 'install iptables'
#  apt:
#    name: 'iptables-persistent'
#    state: 'present'
#
#- name: 'copy iptables config'
#  copy:
#    src: 'rules.v4'
#    dest: '/etc/iptables/rules.v4'
#
#- name: 'manually load iptables config'
#  shell: 'iptables-restore < /etc/iptables/rules.v4'
